// Authentication Action Types
export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// ROLES
export const ROLES_INIT = 'ROLES_INIT';
export const FETCH_ROLES_LIST_SUCCESS = 'FETCH_ROLES_LIST_SUCCESS';
export const FETCH_ROLES_LIST_FAILURE = 'FETCH_ROLES_LIST_FAILURE';
export const FETCH_ROLES_SINGLE_SUCCESS = 'FETCH_ROLES_SINGLE_SUCCESS';
export const FETCH_ROLES_SINGLE_FAILURE = 'FETCH_ROLES_SINGLE_FAILURE';
export const CREATE_ROLES_SUCCESS = 'CREATE_ROLES_SUCCESS';
export const CREATE_ROLES_FAILURE = 'CREATE_ROLES_FAILURE';
export const UPDATE_ROLES_SUCCESS = 'UPDATE_ROLES_SUCCESS';
export const UPDATE_ROLES_FAILURE = 'UPDATE_ROLES_FAILURE';
export const DELETE_ROLES_SUCCESS = 'DELETE_ROLES_SUCCESS';
export const DELETE_ROLES_FAILURE = 'DELETE_ROLES_FAILURE';

// PERMISSIONS
export const PERMISSIONS_INIT = 'PERMISSIONSINIT';
export const FETCH_PERMISSIONS_LIST_SUCCESS = 'FETCH_PERMISSIONSLIST_SUCCESS';
export const FETCH_PERMISSIONS_LIST_FAILURE = 'FETCH_PERMISSIONSLIST_FAILURE';

// USER
export const USER_INIT = 'USER_INIT';
export const FETCH_USER_LIST_SUCCESS = 'FETCH_USER_LIST_SUCCESS';
export const FETCH_USER_LIST_FAILURE = 'FETCH_USER_LIST_FAILURE';
export const FETCH_USER_SINGLE_SUCCESS = 'FETCH_USER_SINGLE_SUCCESS';
export const FETCH_USER_SINGLE_FAILURE = 'FETCH_USER_SINGLE_FAILURE';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

// Department
export const DEPARTMENT_INIT = 'DEPARTMENT_INIT';
export const FETCH_DEPARTMENTS_LIST_SUCCESS = 'FETCH_DEPARTMENTS_LIST_SUCCESS';
export const FETCH_DEPARTMENTS_LIST_FAILURE = 'FETCH_DEPARTMENTS_LIST_FAILURE';
export const FETCH_DEPARTMENT_SINGLE_SUCCESS = 'FETCH_DEPARTMENT_SINGLE_SUCCESS';
export const FETCH_DEPARTMENT_SINGLE_FAILURE = 'FETCH_DEPARTMENT_SINGLE_FAILURE';
export const CREATE_DEPARTMENT_SUCCESS = 'CREATE_DEPARTMENT_SUCCESS';
export const CREATE_DEPARTMENT_FAILURE = 'CREATE_DEPARTMENT_FAILURE';
export const UPDATE_DEPARTMENT_SUCCESS = 'UPDATE_DEPARTMENT_SUCCESS';
export const UPDATE_DEPARTMENT_FAILURE = 'UPDATE_DEPARTMENT_FAILURE';
export const DELETE_DEPARTMENT_SUCCESS = 'DELETE_DEPARTMENT_SUCCESS';
export const DELETE_DEPARTMENT_FAILURE = 'DELETE_DEPARTMENT_FAILURE';


// Checklist
export const CHECKLIST_INIT = 'CHECKLIST_INIT';
export const FETCH_CHECKLISTS_LIST_SUCCESS = 'FETCH_CHECKLISTS_LIST_SUCCESS';
export const FETCH_CHECKLISTS_LIST_FAILURE = 'FETCH_CHECKLISTS_LIST_FAILURE';
export const FETCH_CHECKLIST_SINGLE_SUCCESS = 'FETCH_CHECKLIST_SINGLE_SUCCESS';
export const FETCH_CHECKLIST_SINGLE_FAILURE = 'FETCH_CHECKLIST_SINGLE_FAILURE';
export const CREATE_CHECKLIST_SUCCESS = 'CREATE_CHECKLIST_SUCCESS';
export const CREATE_CHECKLIST_FAILURE = 'CREATE_CHECKLIST_FAILURE';
export const UPDATE_CHECKLIST_SUCCESS = 'UPDATE_CHECKLIST_SUCCESS';
export const UPDATE_CHECKLIST_FAILURE = 'UPDATE_CHECKLIST_FAILURE';
export const DELETE_CHECKLIST_SUCCESS = 'DELETE_CHECKLIST_SUCCESS';
export const DELETE_CHECKLIST_FAILURE = 'DELETE_CHECKLIST_FAILURE';

// Unit
export const UNIT_INIT = 'UNIT_INIT';
export const FETCH_UNITS_LIST_SUCCESS = 'FETCH_UNITS_LIST_SUCCESS';
export const FETCH_UNITS_LIST_FAILURE = 'FETCH_UNITS_LIST_FAILURE';
export const FETCH_UNIT_SINGLE_SUCCESS = 'FETCH_UNIT_SINGLE_SUCCESS';
export const FETCH_UNIT_SINGLE_FAILURE = 'FETCH_UNIT_SINGLE_FAILURE';
export const CREATE_UNIT_SUCCESS = 'CREATE_UNIT_SUCCESS';
export const CREATE_UNIT_FAILURE = 'CREATE_UNIT_FAILURE';
export const UPDATE_UNIT_SUCCESS = 'UPDATE_UNIT_SUCCESS';
export const UPDATE_UNIT_FAILURE = 'UPDATE_UNIT_FAILURE';
export const DELETE_UNIT_SUCCESS = 'DELETE_UNIT_SUCCESS';
export const DELETE_UNIT_FAILURE = 'DELETE_UNIT_FAILURE';

// Warehouse
export const WAREHOUSE_INIT = 'WAREHOUSE_INIT';
export const FETCH_WAREHOUSES_LIST_SUCCESS = 'FETCH_WAREHOUSES_LIST_SUCCESS';
export const FETCH_WAREHOUSES_LIST_FAILURE = 'FETCH_WAREHOUSES_LIST_FAILURE';
export const FETCH_WAREHOUSE_SINGLE_SUCCESS = 'FETCH_WAREHOUSE_SINGLE_SUCCESS';
export const FETCH_WAREHOUSE_SINGLE_FAILURE = 'FETCH_WAREHOUSE_SINGLE_FAILURE';
export const CREATE_WAREHOUSE_SUCCESS = 'CREATE_WAREHOUSE_SUCCESS';
export const CREATE_WAREHOUSE_FAILURE = 'CREATE_WAREHOUSE_FAILURE';
export const UPDATE_WAREHOUSE_SUCCESS = 'UPDATE_WAREHOUSE_SUCCESS';
export const UPDATE_WAREHOUSE_FAILURE = 'UPDATE_WAREHOUSE_FAILURE';
export const DELETE_WAREHOUSE_SUCCESS = 'DELETE_WAREHOUSE_SUCCESS';
export const DELETE_WAREHOUSE_FAILURE = 'DELETE_WAREHOUSE_FAILURE';

// Material Type
export const MATERIAL_TYPE_INIT = 'MATERIAL_TYPE_INIT';
export const FETCH_MATERIAL_TYPES_LIST_SUCCESS = 'FETCH_MATERIAL_TYPES_LIST_SUCCESS';
export const FETCH_MATERIAL_TYPES_LIST_FAILURE = 'FETCH_MATERIAL_TYPES_LIST_FAILURE';
export const FETCH_MATERIAL_TYPE_SINGLE_SUCCESS = 'FETCH_MATERIAL_TYPE_SINGLE_SUCCESS';
export const FETCH_MATERIAL_TYPE_SINGLE_FAILURE = 'FETCH_MATERIAL_TYPE_SINGLE_FAILURE';
export const CREATE_MATERIAL_TYPE_SUCCESS = 'CREATE_MATERIAL_TYPE_SUCCESS';
export const CREATE_MATERIAL_TYPE_FAILURE = 'CREATE_MATERIAL_TYPE_FAILURE';
export const UPDATE_MATERIAL_TYPE_SUCCESS = 'UPDATE_MATERIAL_TYPE_SUCCESS';
export const UPDATE_MATERIAL_TYPE_FAILURE = 'UPDATE_MATERIAL_TYPE_FAILURE';
export const DELETE_MATERIAL_TYPE_SUCCESS = 'DELETE_MATERIAL_TYPE_SUCCESS';
export const DELETE_MATERIAL_TYPE_FAILURE = 'DELETE_MATERIAL_TYPE_FAILURE';



// Production Plant
export const PRODUCTION_PLANT_INIT = 'PRODUCTION_PLANT_INIT';
export const FETCH_PRODUCTION_PLANTS_LIST_SUCCESS = 'FETCH_PRODUCTION_PLANTS_LIST_SUCCESS';
export const FETCH_PRODUCTION_PLANTS_LIST_FAILURE = 'FETCH_PRODUCTION_PLANTS_LIST_FAILURE';
export const FETCH_PRODUCTION_PLANT_SINGLE_SUCCESS = 'FETCH_PRODUCTION_PLANT_SINGLE_SUCCESS';
export const FETCH_PRODUCTION_PLANT_SINGLE_FAILURE = 'FETCH_PRODUCTION_PLANT_SINGLE_FAILURE';
export const CREATE_PRODUCTION_PLANT_SUCCESS = 'CREATE_PRODUCTION_PLANT_SUCCESS';
export const CREATE_PRODUCTION_PLANT_FAILURE = 'CREATE_PRODUCTION_PLANT_FAILURE';
export const UPDATE_PRODUCTION_PLANT_SUCCESS = 'UPDATE_PRODUCTION_PLANT_SUCCESS';
export const UPDATE_PRODUCTION_PLANT_FAILURE = 'UPDATE_PRODUCTION_PLANT_FAILURE';
export const DELETE_PRODUCTION_PLANT_SUCCESS = 'DELETE_PRODUCTION_PLANT_SUCCESS';
export const DELETE_PRODUCTION_PLANT_FAILURE = 'DELETE_PRODUCTION_PLANT_FAILURE';


// Materials
export const MATERIAL_INIT = 'MATERIAL_INIT';
export const FETCH_MATERIALS_PROCESS_LIST_SUCCESS = 'FETCH_MATERIALS_PROCESS_LIST_SUCCESS';
export const FETCH_MATERIALS_PROCESS_LIST_FAILURE = 'FETCH_MATERIALS_PROCESS_LIST_FAILURE';
export const FETCH_MATERIALS_LIST_SUCCESS = 'FETCH_MATERIALS_LIST_SUCCESS';
export const FETCH_MATERIALS_LIST_FAILURE = 'FETCH_MATERIALS_LIST_FAILURE';
export const FETCH_MATERIAL_SINGLE_SUCCESS = 'FETCH_MATERIAL_SINGLE_SUCCESS';
export const FETCH_MATERIAL_SINGLE_FAILURE = 'FETCH_MATERIAL_SINGLE_FAILURE';
export const CREATE_MATERIAL_SUCCESS = 'CREATE_MATERIAL_SUCCESS';
export const CREATE_MATERIAL_FAILURE = 'CREATE_MATERIAL_FAILURE';
export const UPDATE_MATERIAL_SUCCESS = 'UPDATE_MATERIAL_SUCCESS';
export const UPDATE_MATERIAL_FAILURE = 'UPDATE_MATERIAL_FAILURE';
export const DELETE_MATERIAL_SUCCESS = 'DELETE_MATERIAL_SUCCESS';
export const DELETE_MATERIAL_FAILURE = 'DELETE_MATERIAL_FAILURE';


// Purchase Order
export const PURCHASE_ORDER_INIT = 'PURCHASE_ORDER_INIT';
export const FETCH_PURCHASE_ORDERS_LIST_SUCCESS = 'FETCH_PURCHASE_ORDERS_LIST_SUCCESS';
export const FETCH_PURCHASE_ORDERS_LIST_FAILURE = 'FETCH_PURCHASE_ORDERS_LIST_FAILURE';
export const FETCH_PURCHASE_ORDER_SINGLE_SUCCESS = 'FETCH_PURCHASE_ORDER_SINGLE_SUCCESS';
export const FETCH_PURCHASE_ORDER_SINGLE_FAILURE = 'FETCH_PURCHASE_ORDER_SINGLE_FAILURE';
export const CREATE_PURCHASE_ORDER_SUCCESS = 'CREATE_PURCHASE_ORDER_SUCCESS';
export const CREATE_PURCHASE_ORDER_FAILURE = 'CREATE_PURCHASE_ORDER_FAILURE';
export const UPDATE_PURCHASE_ORDER_SUCCESS = 'UPDATE_PURCHASE_ORDER_SUCCESS';
export const UPDATE_PURCHASE_ORDER_FAILURE = 'UPDATE_PURCHASE_ORDER_FAILURE';
export const DELETE_PURCHASE_ORDER_SUCCESS = 'DELETE_PURCHASE_ORDER_SUCCESS';
export const DELETE_PURCHASE_ORDER_FAILURE = 'DELETE_PURCHASE_ORDER_FAILURE';

// Products
export const PRODUCTS_INIT = 'PRODUCTS_INIT';
export const FETCH_PRODUCTS_LIST_SUCCESS = 'FETCH_PRODUCTS_LIST_SUCCESS';
export const FETCH_PRODUCTS_LIST_FAILURE = 'FETCH_PRODUCTS_LIST_FAILURE';
export const FETCH_PRODUCT_SINGLE_SUCCESS = 'FETCH_PRODUCT_SINGLE_SUCCESS';
export const FETCH_PRODUCT_SINGLE_FAILURE = 'FETCH_PRODUCT_SINGLE_FAILURE';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE';


// Production
export const PRODUCTION_INIT = 'PRODUCTION_INIT';
export const FETCH_PRODUCTIONS_LIST_SUCCESS = 'FETCH_PRODUCTIONS_LIST_SUCCESS';
export const FETCH_PRODUCTIONS_LIST_FAILURE = 'FETCH_PRODUCTIONS_LIST_FAILURE';
export const FETCH_PRODUCTION_SINGLE_SUCCESS = 'FETCH_PRODUCTION_SINGLE_SUCCESS';
export const FETCH_PRODUCTION_SINGLE_FAILURE = 'FETCH_PRODUCTION_SINGLE_FAILURE';
export const CREATE_PRODUCTION_SUCCESS = 'CREATE_PRODUCTION_SUCCESS';
export const CREATE_PRODUCTION_FAILURE = 'CREATE_PRODUCTION_FAILURE';
export const UPDATE_PRODUCTION_SUCCESS = 'UPDATE_PRODUCTION_SUCCESS';
export const UPDATE_PRODUCTION_FAILURE = 'UPDATE_PRODUCTION_FAILURE';
export const DELETE_PRODUCTION_SUCCESS = 'DELETE_PRODUCTION_SUCCESS';
export const DELETE_PRODUCTION_FAILURE = 'DELETE_PRODUCTION_FAILURE';

// Recipe
export const RECIPE_INIT = 'RECIPE_INIT';
export const FETCH_RECIPES_LIST_SUCCESS = 'FETCH_RECIPES_LIST_SUCCESS';
export const FETCH_RECIPES_LIST_FAILURE = 'FETCH_RECIPES_LIST_FAILURE';
export const FETCH_RECIPE_SINGLE_SUCCESS = 'FETCH_RECIPE_SINGLE_SUCCESS';
export const FETCH_RECIPE_SINGLE_FAILURE = 'FETCH_RECIPE_SINGLE_FAILURE';
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const CREATE_RECIPE_FAILURE = 'CREATE_RECIPE_FAILURE';
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_FAILURE = 'UPDATE_RECIPE_FAILURE';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_FAILURE = 'DELETE_RECIPE_FAILURE';

// Requisition
export const REQUISITION_INIT = 'REQUISITION_INIT';
export const FETCH_REQUISITIONS_LIST_SUCCESS = 'FETCH_REQUISITIONS_LIST_SUCCESS';
export const FETCH_REQUISITIONS_LIST_FAILURE = 'FETCH_REQUISITIONS_LIST_FAILURE';
export const FETCH_REQUISITION_SINGLE_SUCCESS = 'FETCH_REQUISITION_SINGLE_SUCCESS';
export const FETCH_REQUISITION_SINGLE_FAILURE = 'FETCH_REQUISITION_SINGLE_FAILURE';
export const CREATE_REQUISITION_SUCCESS = 'CREATE_REQUISITION_SUCCESS';
export const CREATE_REQUISITION_FAILURE = 'CREATE_REQUISITION_FAILURE';
export const UPDATE_REQUISITION_SUCCESS = 'UPDATE_REQUISITION_SUCCESS';
export const UPDATE_REQUISITION_FAILURE = 'UPDATE_REQUISITION_FAILURE';
export const DELETE_REQUISITION_SUCCESS = 'DELETE_REQUISITION_SUCCESS';
export const DELETE_REQUISITION_FAILURE = 'DELETE_REQUISITION_FAILURE';

// Receive Order
export const RECEIVE_ORDERS_INIT = 'RECEIVE_ORDERS_INIT';
export const FETCH_RECEIVE_ORDERS_LIST_SUCCESS = 'FETCH_RECEIVE_ORDERS_LIST_SUCCESS';
export const FETCH_RECEIVE_ORDERS_LIST_FAILURE = 'FETCH_RECEIVE_ORDERS_LIST_FAILURE';
export const FETCH_RECEIVE_ORDER_SINGLE_SUCCESS = 'FETCH_RECEIVE_ORDER_SINGLE_SUCCESS';
export const FETCH_RECEIVE_ORDER_SINGLE_FAILURE = 'FETCH_RECEIVE_ORDER_SINGLE_FAILURE';
export const CREATE_RECEIVE_ORDER_SUCCESS = 'CREATE_RECEIVE_ORDER_SUCCESS';
export const CREATE_RECEIVE_ORDER_FAILURE = 'CREATE_RECEIVE_ORDER_FAILURE';
export const UPDATE_RECEIVE_ORDER_SUCCESS = 'UPDATE_RECEIVE_ORDER_SUCCESS';
export const UPDATE_RECEIVE_ORDER_FAILURE = 'UPDATE_RECEIVE_ORDER_FAILURE';
export const DELETE_RECEIVE_ORDER_SUCCESS = 'DELETE_RECEIVE_ORDER_SUCCESS';
export const DELETE_RECEIVE_ORDER_FAILURE = 'DELETE_RECEIVE_ORDER_FAILURE';

// Wastage
export const WASTAGE_INIT = 'WASTAGE_INIT';
export const FETCH_WASTAGES_LIST_SUCCESS = 'FETCH_WASTAGES_LIST_SUCCESS';
export const FETCH_WASTAGES_LIST_FAILURE = 'FETCH_WASTAGES_LIST_FAILURE';
export const FETCH_WASTAGE_SINGLE_SUCCESS = 'FETCH_WASTAGE_SINGLE_SUCCESS';
export const FETCH_WASTAGE_SINGLE_FAILURE = 'FETCH_WASTAGE_SINGLE_FAILURE';
export const CREATE_WASTAGE_SUCCESS = 'CREATE_WASTAGE_SUCCESS';
export const CREATE_WASTAGE_FAILURE = 'CREATE_WASTAGE_FAILURE';
export const UPDATE_WASTAGE_SUCCESS = 'UPDATE_WASTAGE_SUCCESS';
export const UPDATE_WASTAGE_FAILURE = 'UPDATE_WASTAGE_FAILURE';
export const DELETE_WASTAGE_SUCCESS = 'DELETE_WASTAGE_SUCCESS';
export const DELETE_WASTAGE_FAILURE = 'DELETE_WASTAGE_FAILURE';

